export const OPPOSITES = [
  ["tall", "short"],
  ["big", "small"],
  ["hot", "cold"],
  ["soft", "hard"],
  ["loud", "quiet"],
  ["easy", "difficult"],
  ["happy", "sad"],
  ["low", "high"],
  ["shy", "outgoing"],
  ["clean", "dirty"],
  ["new", "old"],
  ["light", "heavy"],
  ["safe", "dangerous"],
  ["strong", "weak"],
  ["fast", "slow"],
  ["early", "late"],
  ["firm", "soft"],
  ["bright", "dim"],
  ["rich", "poor"],
  ["young", "old"],
  ["wet", "dry"],
  ["full", "empty"],
  ["sharp", "dull"],
  ["thick", "thin"],
  ["wide", "narrow"],
  ["smooth", "rough"],
  ["deep", "shallow"],
  ["noisy", "silent"],
  ["brave", "cowardly"],
  ["modern", "ancient"],
  ["honest", "dishonest"],
  ["open", "closed"],
  ["public", "private"],
  ["accurate", "inaccurate"],
  ["present", "absent"],
  ["true", "false"],
  ["nice", "nasty"],
  ["loose", "tight"],
  ["successful", "unsuccessful"],
  ["important", "unimportant"],
  ["possible", "impossible"],
  ["certain", "uncertain"],
  ["awake", "asleep"],
  ["alive", "dead"],
  ["good", "bad"],
  ["positive", "negative"],
  ["helpful", "harmful"],
  ["friendly", "hostile"],
  ["loyal", "betraying"],
  ["generous", "selfish"],
  ["patient", "impatient"],
  ["optimistic", "pessimistic"],
  ["confident", "shy"],
  ["intelligent", "stupid"],
  ["creative", "uncreative"],
  ["organized", "disorganized"],
  ["talented", "untalented"],
  ["expected", "untalented"],
  ["common", "rare"],
  ["popular", "unpopular"],
  ["necessary", "unnecessary"],
  ["helpful", "unhelpful"],
  ["accurate", "inaccurate"],
  ["real", "fake"],
  ["true", "false"],
  ["logical", "illogical"],
  ["rational", "irrational"],
  ["calm", "chaotic"],
  ["organized", "disorganized"],
  ["complex", "simple"],
  ["abstract", "concrete"],
  ["visible", "invisible"],
  ["permanent", "temporary"],
  ["static", "dynamic"],
  ["stable", "unstable"],
  ["consistent", "inconsistent"],
  ["reliable", "unreliable"],
  ["indoor", "outdoor"],
  ["urban", "rural"],
  ["digital", "analog"],
  ["future", "past"],
  ["conscious", "unconscious"],
  ["physical", "mental"],
  ["internal", "external"],
  ["subjective", "objective"],
  ["theoretical", "practical"],
  ["artificial", "natural"],
  ["synthetic", "organic"],
  ["expensive", "cheap"],
  ["abundant", "scarce"],
  ["superficial", "deep"],
  ["famous", "anonymous"],
  ["public", "private"],
  ["legal", "illegal"],
  ["traditional", "modern"],
  ["classic", "trendy"],
  ["formal", "informal"],
  ["active", "passive"],
  ["introverted", "extroverted"],
  ["optimistic", "pessimistic"],
  ["logical", "emotional"],
  ["realistic", "idealistic"],
  ["independent", "dependent"],
  ["leader", "follower"],
  ["winner", "loser"],
  ["hero", "villain"],
  //weird ones
  ["free", "captured"],
  ["just", "unjust"],
  ["equal", "unequal"],
  ["successful", "failed"],
  ["hopeful", "despairing"],
  ["courageous", "fearful"],
  ["loving", "hateful"],
  ["peaceful", "warlike"],
  ["wise", "foolish"],
  ["honest", "dishonest"],
  ["kind", "cruel"],
  ["patient", "impatient"],
  ["generous", "greedy"],
  ["empathetic", "apathetic"],
  ["humble", "arrogant"],
  ["grateful", "ingrateful"],
  ["optimistic", "pessimistic"],
  ["enthusiastic", "apathetic"],
];
export const ADVERB_NOUN_PAIRS = [
  ["talented celebrity", "untalented celebrity"],
  ["good leader", "bad leader"],
  ["happy child", "sad child"],
  ["rich person", "poor person"],
  ["brave person", "cowardly person"],
  ["fast runner", "slow runner"],
  ["clean room", "dirty room"],
  ["strong athlete", "weak athlete"],
  ["smart student", "dumb student"],
  ["polite guest", "rude guest"],
  ["healthy meal", "unhealthy meal"],
  ["bright light", "dim light"],
  ["loud noise", "quiet noise"],
  ["full glass", "empty glass"],
  ["new car", "old car"],
  ["big house", "small house"],
  ["long journey", "short journey"],
  ["good looking animal", "bad looking animal"],
];

export const GENERAL_NOUNS = [
  "animal",
  "mammal",
  "celebrity",
  "singer",
  "human",
  "leader",
  "object",
  "place",
  "thing",
  "idea",
  "concept",
  "event",
  "time",
  "space",
  "matter",
  "energy",
  "force",
  "motion",
  "sound",
  "color",
  "taste",
  "smell",
  "touch",
  // "sight",
  // "hearing",
  "emotion",
  "thought",
  "feeling",
  "desire",
  "fear",
  "love",
  "hate",
  // "anger",
  // "joy",
  // "sadness",
  // "surprise",
  // "disgust",
  // "trust",
  // "distrust",
  // "hope",
  // "despair",
  // "faith",
  // "doubt",
  // "belief",
  // "knowledge",
  // "wisdom",
  // "intelligence",
  // "creativity",
  // "imagination",
  // "memory",
  "language",
  // "communication",
  "technology",
  // "science",
  "art",
  "music",
  "literature",
  "philosophy",
  "religion",
  "politics",
  "economics",
  "history",
  "geography",
  "mathematics",
  "science",
  "technology",
  // "engineering",
  // "medicine",
  // "law",
  "business",
  // "education",
  // "sports",
  // "entertainment",
  // "fashion",
  // "food",
  // "drink",
  // "housing",
  // "transportation",
  // "communication",
  // "government",
  // "economy",
  // "society",
  // "culture",
  // "environment",
  // "nature",
  // "universe",
  // "world",
  // "country",
  // "city",
  // "town",
  // "village",
  // "home",
  // "family",
  // "friend",
  // "enemy",
  // "stranger",
  // "neighbor",
  // "partner",
  // "team",
  // "group",
  "organization",
  // "community",
  // "society",
  // "culture",
  "civilization",
  // "humanity",
  // "life",
  // "death",
  // "birth",
  // "growth",
  // "change",
  // "creation",
  // "destruction",
  // "transformation",
  // "transition",
  // "challenge",
  // "opportunity",
  // "problem",
  // "solution",
  // "choice",
  // "decision",
  // "action",
  // "reaction",
  // "behavior",
  // "habit",
  // "skill",
  // "talent",
  // "ability",
  // "potential",
  // "limitation",
  // "strength",
  // "weakness",
  // "advantage",
  // "disadvantage",
  // "success",
  // "failure",
  // "victory",
  // "defeat",
  // "win",
  // "loss",
  // "competition",
  // "cooperation",
  // "conflict",
  // "agreement",
  // "negotiation",
  // "compromise",
  // "alliance",
  // "war",
  // "peace",
  // "justice",
  // "injustice",
  // "equality",
  // "inequality",
  // "freedom",
  // "slavery",
  // "democracy",
  // "dictatorship",
  // "capitalism",
  // "socialism",
  // "communism",
  // "anarchy",
  // "religion",
  // "spirituality",
  // "philosophy",
  // "science",
  // "art",
  // "music",
  // "literature",
  // "drama",
  // "film",
  // "television",
  // "radio",
  // "internet",
  // "media",
  // "advertising",
  // "marketing",
  // "public relations",
  // "politics",
  // "government",
  // "law",
  // "business",
  // "economy",
  // "finance",
  // "technology",
  // "science",
  // "medicine",
  // "education",
  // "environment",
  // "nature",
  // "climate",
  // "weather",
  // "geography",
  // "geology",
  // "biology",
  // "chemistry",
  // "physics",
  // "mathematics",
  // "astronomy",
  // "space",
  // "time",
  // "universe",
  // "world",
  // "country",
  // "city",
  // "town",
  // "village",
  // "home",
  // "family",
  // "friend",
  // "enemy",
  // "stranger",
  // "neighbor",
  // "partner",
  // "team",
  // "group",
  // "organization",
  // "community",
  // "society",
  // "culture",
  // "civilization",
  // "humanity",
  // "life",
  // "death",
  // "birth",
  // "growth",
  // "change",
  // "progress",
  // "development",
  // "evolution",
  // "revolution",
  // "creation",
  // "destruction",
  // "transformation",
  // "transition",
  // "challenge",
  // "opportunity",
  // "problem",
  // "solution",
  // "choice",
  // "decision",
  // "action",
  // "reaction",
  // "behavior",
  // "habit",
  // "skill",
  // "talent",
  // "ability",
  // "potential",
  // "limitation",
  // "strength",
  // "weakness",
  // "advantage",
  // "disadvantage",
  // "success",
  // "failure",
  // "victory",
  // "defeat",
  // "win",
  // "loss",
  // "competition",
  // "cooperation",
  // "conflict",
  // "agreement",
  // "negotiation",
  // "compromise",
  // "alliance",
  // "war",
  // "peace",
  // "justice",
  // "injustice",
  // "equality",
  // "inequality",
  // "freedom",
  // "slavery",
  // "democracy",
  // "dictatorship",
  // "capitalism",
  // "socialism",
  // "communism",
  // "anarchy",
  // "religion",
  // "spirituality",
  // "philosophy",
  // "science",
  // "art",
  // "music",
  // "literature",
  // "drama",
  // "film",
  // "television",
  // "radio",
  // "internet",
  // "media",
  // "advertising",
  // "marketing",
  // "public relations",
  // "politics",
  // "government",
  // "law",
  // "business",
  //   "economy",
  // "finance",
  // "technology",
  // "science",
  // "medicine",
  // "education",
  // "environment",
  // "nature",
  // "climate",
  // "weather",
  // "geography",
  // "geology",
  // "biology",
  // "chemistry",
  // "physics",
  // "mathematics",
  // "astronomy",
  // "space",
  // "time",
  // "universe",
  // "world",
  "country",
  // "city",
  // "town",
  // "village",
  // "home",
  // "family",
  // "friend",
  // "enemy",
  // "stranger",
  // "neighbor",
  // "partner",
  // "team",
  // "group",
  // "organization",
  // "community",
  // "society",
  // "culture",
  // "civilization",
  // "humanity",
  // "life",
  // "death",
  // "birth",
  // "growth",
  // "change",
  // "progress",
  "development",
  // "evolution",
  // "revolution",
  // "creation",
  // "destruction",
  // "transformation",
  // "transition",
  "challenge",
  // "opportunity",
  "problem",
  "solution",
  // "choice",
  // "decision",
  "action",
  "reaction",
  "behavior",
  "habit",
  "skill",
  // "talent",
  // "ability",
  // "potential",
  // "limitation",
  // "strength",
  // "weakness",
  // "advantage",
  // "disadvantage",
  // "success",
  // "failure",
  // "victory",
  // "defeat",
  // "win",
  // "loss",
  // "competition",
  // "cooperation",
  // "conflict",
  // "agreement",
  // "negotiation",
  // "compromise",
  // "alliance",
  // "war",
  // "peace",
  // "justice",
  // "injustice",
];

export const ORIGINAL_OPPOSITES = [
  ["highly addictive", "mildly addictive"],
  ["cold", "hot"],
  ["weird", "normal"],
  ["colorful", "colorless"],
  ["high calorie", "low calorie"],
  ["feels good", "feels bad"],
  ["essential", "inessential"],
  ["expensive", "cheap"],
  ["overrated weapon", "underrated weapon"],
  ["common", "rare"],
  ["hard subject", "easy subject"],
  ["famous", "unknown"],
  ["easy to use", "difficult to use"],
  ["wired", "normal"],
  ["clean", "dirty"],
  ["requires skill", "requires luck"],
  ["flavorful", "flavorless"],
  ["fascinating topic", "boring topic"],
  ["good actors", "bad actors"],
  ["hipster", "basic"],
  ["safe job", "dangerous job"],
  ["sci-fi", "fantasy"],
  ["formal", "casual"],
  ["overpaid", "underpaid"],
  ["wet", "dry"],
  ["overrated skill", "underrated skill"],
  ["encouraged", "forbidden"],
  ["happy song", "sad song"],
  ["durable", "fragile"],
  ["dork", "geek"],
  ["evil", "good"],
  ["best day of the year", "worst day of the year"],
  ["good habit", "bad habit"],
  ["dog person", "cat person"],
  ["openly love", "guilty pleasure"],
  ["talented", "untalented"],
  ["light", "dark"],
  ["overrated actor", "underrated actor"],
  ["easy to find", "hard to find"],
  ["beautiful man", "ugly man"],
  ["easy to remember", "hard to remember"],
  ["highbrow", "lowbrow"],
  ["healthy", "unhealthy"],
  ["good man", "bad man"],
  ["historically irrelevant", "historically important"],
  ["hairy", "hairless"],
  ["flexible", "inflexible"],
  ["exotic pet", "normal pet"],
  ["extrovert", "introvert"],
  ["movie was better", "book was better"],
  ["good movie", "bad movie"],
  ["beautiful", "ugly"],
  ["happens suddenly", "happens slowly"],
  ["career", "job"],
  ["hated", "loved"],
  ["The Dark Side of the Force", "The Light Side of the Force"],
  ["good pizza topping", "bad pizza topping"],
  ["utopia", "dystopia"],
  ["immature person", "mature person"],
  ["overrated thing to own", "underrated thing to own"],
  ["nice person", "mean person"],
  ["adventure movie", "action movie"],
  ["good", "bad"],
  ["sexy", "unsexy"],
  ["wired", "tired"],
  ["believable", "unbelievable"],
  ["classy", "trashy"],
  ["permanent", "temporary"],
  ["doesn't look like a person", "looks like a person"],
  ["tastes good", "tastes bad"],
  ["game", "sport"],
  ["cool", "uncool"],
  ["greatest living person", "worst living person"],
  ["overrated", "underrated"],
  ["clean food", "messy food"],
  ["ethical", "unethical"],
  ["good gift", "bad gift"],
  ["fashionable", "unfashionable"],
  ["terrorist", "freedom fighter"],
  ["forgiveable", "unforgiveable"],
  ["harmful", "harmless"],
  ["hygienic", "unhygienic"],
  ["good music", "bad music"],
  ["useful", "useless"],
  ["art", "movie that Godzilla would ruin"],
  ["important", "unimportant"],
  ["hard to spell", "easy to spell"],
  ["virtue", "vice"],
  ["overrated musician", "underrated musician"],
  ["popular activity", "unpopular activity"],
  ["whole", "divided"],
  ["reliable", "unreliable"],
  ["hard to kill", "easy to kill"],
  ["stable", "unstable"],
  ["pointy animal", "round animal"],
  ["good TV show", "bad TV show"],
  ["traditionally feminine", "traditionally masculine"],
  ["useful body part", "useless body part"],
  ["classic", "fad"],
  ["brilliant", "stupid"],
  ["strong", "weak"],
  ["useful invention", "useless invention"],
  ["conservative", "liberal"],
  ["popular", "unpopular"],
  ["enemy", "friend"],
  ["exciting", "boring"],
  ["smelly in a good way", "smelly in a bad way"],
  ["hero", "villain"],
  ["overrated thing to do", "underrated thing to do"],
  ["useful in an emergency", "useless in an emergency"],
  ["for adults", "for kids"],
  ["hard to do", "easy to do"],
  ["priceless", "worthless"],
  ["nurture", "nature"],
  ["democracy", "dictatorship"],
  ["weird greeting", "normal greeting"],
  ["cat name", "dog name"],
  ["partisan", "non-partisan"],
  ["infinite", "limited"],
  ["formal event", "casual event"],
  ["good investment", "bad investment"],
  ["heavy topic", "small talk"],
  ["spicy", "mild"],
  ["sacrilegious", "religious"],
  ["art", "not art"],
  ["prohibited", "illegal"],
  ["elitist", "popular"],
  ["in control", "out of control"],
  ["loud", "quiet"],
  ["public knowledge", "secret"],
  ["too big", "too small"],
  ["long", "short"],
  ["best year in history", "worst year in history"],
  ["capitalist", "socialist"],
  ["well known fact", "little known fact"],
  ["mobile", "stationary"],
  ["global issue", "local issue"],
  ["skill", "talent"],
  ["best era to time travel", "worst era to time travel"],
  ["the best", "the worst"],
  ["large number", "small number"],
  ["false", "true"],
  ["avant garde", "old fashioned"],
  ["beautiful word", "ugly word"],
  ["tiny", "small"],
  ["natural", "unnatural"],
  ["phony person", "genuine person"],
  ["original", "derivative"],
  ["sexy color", "unsexy color"],
  ["benefits everyone", "benefits you"],
  ["powerful", "powerless"],
  ["vapes", "doesn’t vape"],
  ["vegetable", "fruit"],
  ["pseudoscience", "science"],
  ["serious topic", "funny topic"],
  ["firm", "limp"],
  ["news", "gossip"],
  ["easy to sit on", "hard to sit on"],
  ["too much", "not enough"],
  ["vertical", "horizontal"],
  ["scented", "unscented"],
  ["not huggable", "huggable"],
  ["homogenous", "heterogeneous"],
  ["exclusive", "inclusive"],
  ["good dog breed", "bad dog breed"],
  ["commerce", "art"],
  ["pop icon", "one hit wonder"],
  ["good advice", "bad advice"],
  ["good candy", "bad candy"],
  ["radical", "traditional"],
  ["good mouthfeel", "bad mouthfeel"],
  ["legal", "illegal"],
  ["shallow thought", "deep thought"],
  ["good school", "bad school"],
  ["always on time", "never on time"],
  ["will live to 100", "won’t live to 100"],
  ["good Disney character", "bad Disney character"],
  ["good president", "bad president"],
  ["strange", "weird"],
  ["infamous", "famous"],
  ["most powerful god", "least powerful god"],
  ["fun person", "boring person"],
  ["overrated book", "underrated book"],
  ["best chore", "worst chore"],
  ["overpopulated species", "endangered species"],
  ["green", "blue"],
  ["terrifying", "thrilling"],
  ["unexpected", "expected"],
  ["person who’d beat you up", "person you could beat up"],
  ["overrated game", "underrated game"],
  [
    "you don’t want your parents to watch you do it",
    "you want your parents to watch you do it",
  ],
  ["evil people", "good people"],
  ["jock", "nerd"],
];

export const COMBINED = [...OPPOSITES, ...ADVERB_NOUN_PAIRS];
