export const OPPOSITES = [
  ["tall", "short"],
  ["big", "small"],
  ["hot", "cold"],
  ["soft", "hard"],
  ["loud", "quiet"],
  ["easy", "difficult"],
  ["happy", "sad"],
  ["low", "high"],
  ["shy", "outgoing"],
  ["clean", "dirty"],
  ["new", "old"],
  ["light", "heavy"],
  ["safe", "dangerous"],
  ["strong", "weak"],
  ["fast", "slow"],
  ["early", "late"],
  ["firm", "soft"],
  ["bright", "dim"],
  ["rich", "poor"],
  ["young", "old"],
  ["wet", "dry"],
  ["full", "empty"],
  ["sharp", "dull"],
  ["thick", "thin"],
  ["wide", "narrow"],
  ["smooth", "rough"],
  ["deep", "shallow"],
  ["noisy", "silent"],
  ["brave", "cowardly"],
  ["modern", "ancient"],
  ["honest", "dishonest"],
  ["open", "closed"],
  ["public", "private"],
  ["accurate", "inaccurate"],
  ["present", "absent"],
  ["true", "false"],
  ["nice", "nasty"],
  ["loose", "tight"],
  ["successful", "unsuccessful"],
  ["important", "unimportant"],
  ["possible", "impossible"],
  ["certain", "uncertain"],
  ["awake", "asleep"],
  ["alive", "dead"],
  ["good", "bad"],
  ["positive", "negative"],
  ["helpful", "harmful"],
  ["friendly", "hostile"],
  ["loyal", "betraying"],
  ["generous", "selfish"],
  ["patient", "impatient"],
  ["optimistic", "pessimistic"],
  ["confident", "shy"],
  ["intelligent", "stupid"],
  ["creative", "uncreative"],
  ["organized", "disorganized"],
  ["talented", "untalented"],
  ["expected", "untalented"],
  ["common", "rare"],
  ["popular", "unpopular"],
  ["necessary", "unnecessary"],
  ["helpful", "unhelpful"],
  ["accurate", "inaccurate"],
  ["real", "fake"],
  ["true", "false"],
  ["logical", "illogical"],
  ["rational", "irrational"],
  ["calm", "chaotic"],
  ["organized", "disorganized"],
  ["complex", "simple"],
  ["abstract", "concrete"],
  ["visible", "invisible"],
  ["permanent", "temporary"],
  ["static", "dynamic"],
  ["stable", "unstable"],
  ["consistent", "inconsistent"],
  ["reliable", "unreliable"],
  ["indoor", "outdoor"],
  ["urban", "rural"],
  ["digital", "analog"],
  ["future", "past"],
  ["conscious", "unconscious"],
  ["physical", "mental"],
  ["internal", "external"],
  ["subjective", "objective"],
  ["theoretical", "practical"],
  ["artificial", "natural"],
  ["synthetic", "organic"],
  ["expensive", "cheap"],
  ["abundant", "scarce"],
  ["superficial", "deep"],
  ["famous", "anonymous"],
  ["public", "private"],
  ["legal", "illegal"],
  ["traditional", "modern"],
  ["classic", "trendy"],
  ["formal", "informal"],
  ["active", "passive"],
  ["introverted", "extroverted"],
  ["optimistic", "pessimistic"],
  ["logical", "emotional"],
  ["realistic", "idealistic"],
  ["independent", "dependent"],
  ["leader", "follower"],
  ["winner", "loser"],
  ["hero", "villain"],
  //weird ones
  ["free", "captured"],
  ["just", "unjust"],
  ["equal", "unequal"],
  ["successful", "failed"],
  ["hopeful", "despairing"],
  ["courageous", "fearful"],
  ["loving", "hateful"],
  ["peaceful", "warlike"],
  ["wise", "foolish"],
  ["honest", "dishonest"],
  ["kind", "cruel"],
  ["patient", "impatient"],
  ["generous", "greedy"],
  ["empathetic", "apathetic"],
  ["humble", "arrogant"],
  ["grateful", "ingrateful"],
  ["optimistic", "pessimistic"],
  ["enthusiastic", "apathetic"],
];
export const ADVERB_NOUN_PAIRS = [
  ["talented celebrity", "untalented celebrity"],
  ["good leader", "bad leader"],
  ["happy child", "sad child"],
  ["rich person", "poor person"],
  ["brave person", "cowardly person"],
  ["fast runner", "slow runner"],
  ["clean room", "dirty room"],
  ["strong athlete", "weak athlete"],
  ["smart student", "dumb student"],
  ["polite guest", "rude guest"],
  ["healthy meal", "unhealthy meal"],
  ["bright light", "dim light"],
  ["loud noise", "quiet noise"],
  ["full glass", "empty glass"],
  ["new car", "old car"],
  ["big house", "small house"],
  ["long journey", "short journey"],
  ["good looking animal", "bad looking animal"],
];

export const GENERAL_NOUNS = [
  "animal",
  "mammal",
  "celebrity",
  "singer",
  "human",
  "leader",
  "object",
  "place",
  "thing",
  "idea",
  "concept",
  "event",
  "time",
  "space",
  "matter",
  "energy",
  "force",
  "motion",
  "sound",
  "color",
  "taste",
  "smell",
  "touch",
  // "sight",
  // "hearing",
  "emotion",
  "thought",
  "feeling",
  "desire",
  "fear",
  "love",
  "hate",
  // "anger",
  // "joy",
  // "sadness",
  // "surprise",
  // "disgust",
  // "trust",
  // "distrust",
  // "hope",
  // "despair",
  // "faith",
  // "doubt",
  // "belief",
  // "knowledge",
  // "wisdom",
  // "intelligence",
  // "creativity",
  // "imagination",
  // "memory",
  "language",
  // "communication",
  "technology",
  // "science",
  "art",
  "music",
  "literature",
  "philosophy",
  "religion",
  "politics",
  "economics",
  "history",
  "geography",
  "mathematics",
  "science",
  "technology",
  // "engineering",
  // "medicine",
  // "law",
  "business",
  // "education",
  // "sports",
  // "entertainment",
  // "fashion",
  // "food",
  // "drink",
  // "housing",
  // "transportation",
  // "communication",
  // "government",
  // "economy",
  // "society",
  // "culture",
  // "environment",
  // "nature",
  // "universe",
  // "world",
  // "country",
  // "city",
  // "town",
  // "village",
  // "home",
  // "family",
  // "friend",
  // "enemy",
  // "stranger",
  // "neighbor",
  // "partner",
  // "team",
  // "group",
  "organization",
  // "community",
  // "society",
  // "culture",
  "civilization",
  // "humanity",
  // "life",
  // "death",
  // "birth",
  // "growth",
  // "change",
  // "creation",
  // "destruction",
  // "transformation",
  // "transition",
  // "challenge",
  // "opportunity",
  // "problem",
  // "solution",
  // "choice",
  // "decision",
  // "action",
  // "reaction",
  // "behavior",
  // "habit",
  // "skill",
  // "talent",
  // "ability",
  // "potential",
  // "limitation",
  // "strength",
  // "weakness",
  // "advantage",
  // "disadvantage",
  // "success",
  // "failure",
  // "victory",
  // "defeat",
  // "win",
  // "loss",
  // "competition",
  // "cooperation",
  // "conflict",
  // "agreement",
  // "negotiation",
  // "compromise",
  // "alliance",
  // "war",
  // "peace",
  // "justice",
  // "injustice",
  // "equality",
  // "inequality",
  // "freedom",
  // "slavery",
  // "democracy",
  // "dictatorship",
  // "capitalism",
  // "socialism",
  // "communism",
  // "anarchy",
  // "religion",
  // "spirituality",
  // "philosophy",
  // "science",
  // "art",
  // "music",
  // "literature",
  // "drama",
  // "film",
  // "television",
  // "radio",
  // "internet",
  // "media",
  // "advertising",
  // "marketing",
  // "public relations",
  // "politics",
  // "government",
  // "law",
  // "business",
  // "economy",
  // "finance",
  // "technology",
  // "science",
  // "medicine",
  // "education",
  // "environment",
  // "nature",
  // "climate",
  // "weather",
  // "geography",
  // "geology",
  // "biology",
  // "chemistry",
  // "physics",
  // "mathematics",
  // "astronomy",
  // "space",
  // "time",
  // "universe",
  // "world",
  // "country",
  // "city",
  // "town",
  // "village",
  // "home",
  // "family",
  // "friend",
  // "enemy",
  // "stranger",
  // "neighbor",
  // "partner",
  // "team",
  // "group",
  // "organization",
  // "community",
  // "society",
  // "culture",
  // "civilization",
  // "humanity",
  // "life",
  // "death",
  // "birth",
  // "growth",
  // "change",
  // "progress",
  // "development",
  // "evolution",
  // "revolution",
  // "creation",
  // "destruction",
  // "transformation",
  // "transition",
  // "challenge",
  // "opportunity",
  // "problem",
  // "solution",
  // "choice",
  // "decision",
  // "action",
  // "reaction",
  // "behavior",
  // "habit",
  // "skill",
  // "talent",
  // "ability",
  // "potential",
  // "limitation",
  // "strength",
  // "weakness",
  // "advantage",
  // "disadvantage",
  // "success",
  // "failure",
  // "victory",
  // "defeat",
  // "win",
  // "loss",
  // "competition",
  // "cooperation",
  // "conflict",
  // "agreement",
  // "negotiation",
  // "compromise",
  // "alliance",
  // "war",
  // "peace",
  // "justice",
  // "injustice",
  // "equality",
  // "inequality",
  // "freedom",
  // "slavery",
  // "democracy",
  // "dictatorship",
  // "capitalism",
  // "socialism",
  // "communism",
  // "anarchy",
  // "religion",
  // "spirituality",
  // "philosophy",
  // "science",
  // "art",
  // "music",
  // "literature",
  // "drama",
  // "film",
  // "television",
  // "radio",
  // "internet",
  // "media",
  // "advertising",
  // "marketing",
  // "public relations",
  // "politics",
  // "government",
  // "law",
  // "business",
  //   "economy",
  // "finance",
  // "technology",
  // "science",
  // "medicine",
  // "education",
  // "environment",
  // "nature",
  // "climate",
  // "weather",
  // "geography",
  // "geology",
  // "biology",
  // "chemistry",
  // "physics",
  // "mathematics",
  // "astronomy",
  // "space",
  // "time",
  // "universe",
  // "world",
  "country",
  // "city",
  // "town",
  // "village",
  // "home",
  // "family",
  // "friend",
  // "enemy",
  // "stranger",
  // "neighbor",
  // "partner",
  // "team",
  // "group",
  // "organization",
  // "community",
  // "society",
  // "culture",
  // "civilization",
  // "humanity",
  // "life",
  // "death",
  // "birth",
  // "growth",
  // "change",
  // "progress",
  "development",
  // "evolution",
  // "revolution",
  // "creation",
  // "destruction",
  // "transformation",
  // "transition",
  "challenge",
  // "opportunity",
  "problem",
  "solution",
  // "choice",
  // "decision",
  "action",
  "reaction",
  "behavior",
  "habit",
  "skill",
  // "talent",
  // "ability",
  // "potential",
  // "limitation",
  // "strength",
  // "weakness",
  // "advantage",
  // "disadvantage",
  // "success",
  // "failure",
  // "victory",
  // "defeat",
  // "win",
  // "loss",
  // "competition",
  // "cooperation",
  // "conflict",
  // "agreement",
  // "negotiation",
  // "compromise",
  // "alliance",
  // "war",
  // "peace",
  // "justice",
  // "injustice",
];

export const COMBINED = [...OPPOSITES, ...ADVERB_NOUN_PAIRS];
