export const OPPOSITES = [
  ["tall", "short"],
  ["big", "small"],
  ["hot", "cold"],
  ["soft", "hard"],
  ["loud", "quiet"],
  ["easy", "difficult"],
  ["happy", "sad"],
  ["low", "high"],
  ["shy", "outgoing"],
  ["clean", "dirty"],
  ["new", "old"],
  ["light", "heavy"],
  ["safe", "dangerous"],
  ["strong", "weak"],
  ["fast", "slow"],
  ["early", "late"],
  ["firm", "soft"],
  ["bright", "dim"],
  ["rich", "poor"],
  ["young", "old"],
  ["wet", "dry"],
  ["full", "empty"],
  ["sharp", "dull"],
  ["thick", "thin"],
  ["wide", "narrow"],
  ["smooth", "rough"],
  ["deep", "shallow"],
  ["noisy", "silent"],
  ["brave", "cowardly"],
  ["modern", "ancient"],
  ["honest", "dishonest"],
  ["open", "closed"],
  ["public", "private"],
  ["accurate", "inaccurate"],
  ["present", "absent"],
  ["successful", "unsuccessful"],
  ["important", "unimportant"],
  ["possible", "impossible"],
  ["certain", "uncertain"],
  // ["awake", "asleep"],
  ["alive", "dead"],
  ["good", "bad"],
  ["positive", "negative"],
  ["helpful", "harmful"],
  ["friendly", "hostile"],
  ["loyal", "betraying"],
  ["generous", "selfish"],
  ["patient", "impatient"],
  //   ["optimistic", "pessimistic"],
  ["confident", "shy"],
  ["intelligent", "stupid"],
  //   ["creative", "uncreative"],
  ["organized", "disorganized"],
];
